const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const publicRoot = path.join(root, 'public');
const requiredFiles = ['public/index.html','public/src/app.js','public/src/styles.css','public/manifest.json','public/service-worker.js','public/assets/icons/icon.svg','public/assets/audio/audio-manifest.json','public/data/zhuyin.json','public/data/characters.json','public/data/words.json','public/data/categories.json','public/.assetsignore','.github/workflows/validate.yml','wrangler.jsonc','AGENTS.md','PLAN.md','PROGRESS.md','DECISIONS.md','TASKS.md','README.md'];
for (const file of requiredFiles) if (!fs.existsSync(path.join(root, file))) throw new Error(`Missing required file: ${file}`);
for (const internal of ['AGENTS.md','PLAN.md','PROGRESS.md','DECISIONS.md','TASKS.md','MEMORY.md','ARCHITECTURE.md','CHANGELOG.md','README.md']) if (fs.existsSync(path.join(publicRoot, internal))) throw new Error(`Internal document must not be public: ${internal}`);
for (const internalDir of ['.git','.wrangler','tests','reports','.github','node_modules']) if (fs.existsSync(path.join(publicRoot, internalDir))) throw new Error(`Internal directory must not be public: ${internalDir}`);
const wrangler = fs.readFileSync(path.join(root, 'wrangler.jsonc'), 'utf8');
if (!wrangler.includes('"directory": "./public"')) throw new Error('wrangler assets directory must be ./public');
const manifest = JSON.parse(fs.readFileSync(path.join(publicRoot, 'manifest.json'), 'utf8'));
if (manifest.display !== 'standalone') throw new Error('manifest display must be standalone');
if (!manifest.icons?.some((icon) => icon.src === 'assets/icons/icon.svg')) throw new Error('manifest must include SVG icon');
const html = fs.readFileSync(path.join(publicRoot, 'index.html'), 'utf8');
for (const snippet of ['profileView','learnView','cardsView','listenView','wordView','spellView','parentView','data-speech','src="src/app.js"','<ruby>','<rt>']) if (!html.includes(snippet)) throw new Error(`index.html missing ${snippet}`);
if (html.includes('/public/') || html.includes('public/')) throw new Error('index.html must not expose public/ in URLs');
const app = fs.readFileSync(path.join(publicRoot, 'src/app.js'), 'utf8');
for (const snippet of ['APP_VERSION','V1.2.0','AUDIO_MODE = \'system\'','STORAGE_SCHEMA_VERSION = 2','CHILD_PROFILES','林芳伃','林彥宇','林子齊','BUTTON_SPEECH','speakSystemText','stopAllSpeech','playZhuyinSound','playWordSound','zhuyin-current-child','zhuyin-profile-lisa','const symbols = expectedSymbols.map','spellingQuestions','new Audio','serviceWorker','assets/audio/audio-manifest.json','data/characters.json','data/words.json','data/zhuyin.json','ㄓㄜ']) if (!app.includes(snippet)) throw new Error(`public/src/app.js missing ${snippet}`);
const expectedSymbols = 'ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦ'.split('');
for (const expected of expectedSymbols) if (!app.includes(`'${expected}'`)) throw new Error(`missing symbol ${expected}`);
const zhuyin = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/zhuyin.json'), 'utf8'));
if (zhuyin.length !== 37) throw new Error('zhuyin.json must include 37 symbols');
for (const z of zhuyin) for (const field of ['symbol','systemSpeechText','exampleWord','exampleZhuyin','audioKey','recording']) if (!z[field]) throw new Error(`zhuyin item missing ${field}`);
const categories = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/categories.json'), 'utf8'));
if (categories.length !== 17) throw new Error('categories count must be 17');
const chars = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/characters.json'), 'utf8'));
const words = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/words.json'), 'utf8'));
if (chars.length < 300 || chars.length > 500) throw new Error(`characters count out of range: ${chars.length}`);
if (words.length < 200 || words.length > 300) throw new Error(`words count out of range: ${words.length}`);
function validateItems(items, label){ const ids=new Set(); const values=new Set(); for (const item of items){ if(ids.has(item.id)) throw new Error(`${label} duplicate id ${item.id}`); ids.add(item.id); const val=item.word || item.han; if(values.has(label==='words'?item.word:`${item.id}:${item.han}`)) throw new Error(`${label} duplicate value ${val}`); values.add(label==='words'?item.word:`${item.id}:${item.han}`); for (const f of ['han','zhuyin','word','wordCharacters','emoji','category','difficulty','speechText','audioKey']) if (!item[f] || (Array.isArray(item[f]) && !item[f].length)) throw new Error(`${label} item missing ${f}`); if (!categories.includes(item.category)) throw new Error(`${label} invalid category ${item.category}`); if (!item.wordCharacters.every((c)=>c.han && Array.isArray(c.zhuyin) && c.zhuyin.length)) throw new Error(`${label} malformed wordCharacters`); }}
validateItems(chars,'characters'); validateItems(words,'words');
const audioManifest = JSON.parse(fs.readFileSync(path.join(publicRoot, 'assets/audio/audio-manifest.json'), 'utf8'));
if (Object.keys(audioManifest.items || {}).length !== 37) throw new Error('audio manifest must include 37 items');
const sw = fs.readFileSync(path.join(publicRoot, 'service-worker.js'), 'utf8');
for (const snippet of ["zhuyin-bee-v1-2-0", "'/index.html'", "event.request.mode === 'navigate'", 'canCacheResponse', '!response.redirected', "response.type === 'basic'", "startsWith('zhuyin-bee-')", 'caches.delete']) if (!sw.includes(snippet)) throw new Error(`service-worker.js missing ${snippet}`);
if (sw.includes("'./'") || sw.includes('"./"')) throw new Error('service-worker.js must not precache ./');
console.log(`PWA static validation passed. zhuyin=${zhuyin.length}, characters=${chars.length}, words=${words.length}, categories=${categories.length}`);
