const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const publicRoot = path.join(root, 'public');
const requiredFiles = ['public/index.html','public/offline.html','public/src/app.js','public/src/styles.css','public/manifest.json','public/service-worker.js','public/assets/icons/icon.svg','public/assets/audio/audio-manifest.json','public/data/zhuyin.json','public/data/characters.json','public/data/words.json','public/data/categories.json','public/data/media-map.json','public/data/questions.json','public/.assetsignore','.github/workflows/validate.yml','wrangler.jsonc','AGENTS.md','PLAN.md','PROGRESS.md','DECISIONS.md','TASKS.md','README.md','DATABASE.md','API.md','migrations/0001_dictionary.sql','src/worker.js'];
for (const file of requiredFiles) if (!fs.existsSync(path.join(root, file))) throw new Error(`Missing required file: ${file}`);
for (const internal of ['AGENTS.md','PLAN.md','PROGRESS.md','DECISIONS.md','TASKS.md','MEMORY.md','ARCHITECTURE.md','CHANGELOG.md','README.md']) if (fs.existsSync(path.join(publicRoot, internal))) throw new Error(`Internal document must not be public: ${internal}`);
const wrangler = fs.readFileSync(path.join(root, 'wrangler.jsonc'), 'utf8');
for (const snippet of ['"directory": "./public"','"main": "src/worker.js"','"binding": "ASSETS"']) if (!wrangler.includes(snippet)) throw new Error(`wrangler missing ${snippet}`);
if (wrangler.includes('replace-with-cloudflare-d1-database-id') || wrangler.includes('"d1_databases"')) throw new Error('wrangler must not include temporary D1 placeholders before production D1 is created');
const manifest = JSON.parse(fs.readFileSync(path.join(publicRoot, 'manifest.json'), 'utf8'));
if (manifest.display !== 'standalone') throw new Error('manifest display must be standalone');
if (manifest.version !== 'V1.3.2') throw new Error('manifest version must be V1.3.2');
if (!manifest.icons?.some((icon) => icon.src === 'assets/icons/icon.svg')) throw new Error('manifest must include SVG icon');
const html = fs.readFileSync(path.join(publicRoot, 'index.html'), 'utf8');
for (const snippet of ['profileView','learnView','cardsView','listenView','wordView','spellView','parentView','themeTitle','data-child-theme','data-speech','src="src/app.js"','<ruby>','<rt>']) if (!html.includes(snippet)) throw new Error(`index.html missing ${snippet}`);
if (html.includes('/public/') || html.includes('public/')) throw new Error('index.html must not expose public/ in URLs');
const app = fs.readFileSync(path.join(publicRoot, 'src/app.js'), 'utf8');
for (const snippet of ['APP_VERSION','V1.3.2','Asia/Ho_Chi_Minh','AUDIO_MODE = \'system\'','STORAGE_SCHEMA_VERSION = 3','DICTIONARY_SCHEMA_VERSION = 1','CHILD_PROFILES','林芳伃','林彥宇','林子齊','CHILD_THEMES','ACTIVE_THEME','storybook-zoo','BUTTON_BEHAVIOR','speakSystemText','stopAllSpeech','playZhuyinSound','playWordSound','zhuyin-current-child','zhuyin-profile-lisa','const symbols = expectedSymbols.map','SPELLING_BANK','mouth-zui','plane-fei','drink-he','pants-ku','correctOptionId','normalizeZhuyin','data-option-id','clearAppCache','serviceWorker','assets/audio/audio-manifest.json','data/characters.json','data/words.json','data/zhuyin.json','data/media-map.json','data/questions.json','buildVerifiedQuestionPool','renderParentBackupPanel','ㄓㄜ']) if (!app.includes(snippet)) throw new Error(`public/src/app.js missing ${snippet}`);
if (app.includes('聽一聽",()=>playZhuyinSound') || app.includes('data-speech="聽注音"')) throw new Error('content playback buttons must not announce button labels first');
for (const forbidden of ['嘴巴大','褲子大','飛機大','喝水大','喝水小','媽媽小','哥哥小','爸爸小']) if (app.includes(forbidden)) throw new Error(`forbidden spelling text ${forbidden}`);
const expectedSymbols = 'ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦ'.split('');
for (const expected of expectedSymbols) if (!app.includes(`'${expected}'`)) throw new Error(`missing symbol ${expected}`);
const zhuyin = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/zhuyin.json'), 'utf8'));
if (zhuyin.length !== 37) throw new Error('zhuyin.json must include 37 symbols');
const categories = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/categories.json'), 'utf8'));
if (categories.length !== 17) throw new Error('categories count must be 17');
const chars = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/characters.json'), 'utf8'));
const words = JSON.parse(fs.readFileSync(path.join(publicRoot, 'data/words.json'), 'utf8'));
if (chars.length < 12 || chars.length > 80) throw new Error(`characters count out of range: ${chars.length}`);
if (words.length < 12 || words.length > 80) throw new Error(`words count out of range: ${words.length}`);
const sw = fs.readFileSync(path.join(publicRoot, 'service-worker.js'), 'utf8');
for (const snippet of ["zhuyin-zoo-v1-3-2", "'/offline.html'", "event.request.mode === 'navigate'", 'canCacheStaticResponse', '!response.redirected', "response.type === 'basic'", "request.mode !== 'navigate'", "startsWith('zhuyin-bee-')", "startsWith('zhuyin-zoo-')", 'SKIP_WAITING', 'clients.claim']) if (!sw.includes(snippet)) throw new Error(`service-worker.js missing ${snippet}`);
if (sw.includes("'./'") || sw.includes('"./"') || sw.includes("'/'")) throw new Error('service-worker.js must not precache ./ or /');
if (/cache\.put\(event\.request/.test(sw)) throw new Error('navigate event.request must not be cached');
if (!sw.includes("caches.match('/offline.html')")) throw new Error('navigate fallback must use offline.html');
const css = fs.readFileSync(path.join(publicRoot, 'src/styles.css'), 'utf8');
for (const snippet of ['.menu-label','clamp(1.75rem,5vw,2.35rem)','.zhuyin-answer-syllable','.zhuyin-answer-single','.zhuyin-group','.zhuyin-tone','data-child-theme','max-width:390px','prefers-reduced-motion']) if (!css.includes(snippet)) throw new Error(`styles missing ${snippet}`);
console.log(`PWA static validation passed. zhuyin=${zhuyin.length}, characters=${chars.length}, words=${words.length}, categories=${categories.length}`);
