-- D1 dictionary schema version 1 for 注音小蜜蜂 V1.3.0
CREATE TABLE IF NOT EXISTS migration_versions (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS import_sources (id TEXT PRIMARY KEY, source_type TEXT NOT NULL, source_file_name TEXT, source_book TEXT, source_lesson TEXT, imported_at TEXT NOT NULL, review_status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS characters (id TEXT PRIMARY KEY, han TEXT NOT NULL, primary_zhuyin TEXT NOT NULL, category_id TEXT, difficulty TEXT NOT NULL, emoji TEXT, speech_text TEXT, audio_key TEXT, enabled INTEGER NOT NULL DEFAULT 1, source_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(category_id) REFERENCES categories(id), FOREIGN KEY(source_id) REFERENCES import_sources(id));
CREATE TABLE IF NOT EXISTS words (id TEXT PRIMARY KEY, word TEXT NOT NULL UNIQUE, speech_text TEXT NOT NULL, category_id TEXT, difficulty TEXT NOT NULL, emoji TEXT, target_character_id TEXT, enabled INTEGER NOT NULL DEFAULT 1, source_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(category_id) REFERENCES categories(id), FOREIGN KEY(target_character_id) REFERENCES characters(id), FOREIGN KEY(source_id) REFERENCES import_sources(id));
CREATE TABLE IF NOT EXISTS word_characters (id TEXT PRIMARY KEY, word_id TEXT NOT NULL, character_id TEXT, han TEXT NOT NULL, position INTEGER NOT NULL, zhuyin_json TEXT NOT NULL, FOREIGN KEY(word_id) REFERENCES words(id), FOREIGN KEY(character_id) REFERENCES characters(id));
CREATE TABLE IF NOT EXISTS pronunciations (id TEXT PRIMARY KEY, character_id TEXT NOT NULL, context_word_id TEXT, symbols_json TEXT NOT NULL, tone TEXT, normalized TEXT NOT NULL, is_primary INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(character_id) REFERENCES characters(id), FOREIGN KEY(context_word_id) REFERENCES words(id));
CREATE TABLE IF NOT EXISTS import_jobs (id TEXT PRIMARY KEY, source_id TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(source_id) REFERENCES import_sources(id));
CREATE TABLE IF NOT EXISTS import_candidates (id TEXT PRIMARY KEY, import_job_id TEXT NOT NULL, candidate_type TEXT NOT NULL, raw_text TEXT NOT NULL, parsed_json TEXT NOT NULL, validation_status TEXT NOT NULL, review_status TEXT NOT NULL, error_message TEXT, FOREIGN KEY(import_job_id) REFERENCES import_jobs(id));
CREATE TABLE IF NOT EXISTS change_logs (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, before_json TEXT, after_json TEXT, created_at TEXT NOT NULL);
INSERT OR IGNORE INTO migration_versions (version, applied_at) VALUES (1, datetime('now'));
