const JSON_HEADERS = { 'content-type': 'application/json; charset=utf-8' };
const DICTIONARY_SCHEMA_VERSION = 1;
function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: JSON_HEADERS }); }
function requireParentSession(request) { return request.headers.get('x-parent-session') === 'local-parent-session-v1'; }
async function readJson(request) { try { return await request.json(); } catch { return null; } }
function validateCharacter(input) { const errors=[]; if(!input?.han) errors.push('han_required'); if(!input?.primary_zhuyin) errors.push('primary_zhuyin_required'); if(!['beginner','advanced'].includes(input?.difficulty)) errors.push('difficulty_invalid'); return errors; }
function validateWord(input) { const errors=[]; if(!input?.word) errors.push('word_required'); if(!input?.speech_text) errors.push('speech_text_required'); if(!['beginner','advanced'].includes(input?.difficulty)) errors.push('difficulty_invalid'); return errors; }
export default { async fetch(request, env) { const url = new URL(request.url); if (!url.pathname.startsWith('/api/')) return env.ASSETS.fetch(request); if (url.pathname.startsWith('/api/dictionary/') && !env.DB) return json({ error: 'd1_binding_missing', message: 'Cloudflare D1 binding DB is required for dictionary APIs.' }, 503); if (url.pathname === '/api/dictionary/stats') { const [characters, words, categories, pending] = await Promise.all([env.DB.prepare('SELECT COUNT(*) c FROM characters WHERE enabled = 1').first(), env.DB.prepare('SELECT COUNT(*) c FROM words WHERE enabled = 1').first(), env.DB.prepare('SELECT COUNT(*) c FROM categories').first(), env.DB.prepare("SELECT COUNT(*) c FROM import_candidates WHERE review_status = 'pending'").first()]); return json({ schemaVersion: DICTIONARY_SCHEMA_VERSION, zhuyin:37, characters:characters.c, words:words.c, categories:categories.c, pending:pending.c }); }
    if (url.pathname === '/api/dictionary/characters' && request.method === 'GET') { const rows = await env.DB.prepare('SELECT * FROM characters ORDER BY updated_at DESC LIMIT 200').all(); return json({ items: rows.results }); }
    if (url.pathname === '/api/dictionary/characters' && request.method === 'POST') { if(!requireParentSession(request)) return json({ error:'parent_session_required' }, 401); const body=await readJson(request); const errors=validateCharacter(body); if(errors.length) return json({ errors }, 400); const id=body.id || crypto.randomUUID(); await env.DB.prepare('INSERT INTO characters (id,han,primary_zhuyin,category_id,difficulty,emoji,speech_text,audio_key,enabled,source_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,datetime("now"),datetime("now"))').bind(id, body.han, body.primary_zhuyin, body.category_id||null, body.difficulty, body.emoji||null, body.speech_text||body.han, body.audio_key||id, body.enabled===false?0:1, body.source_id||null).run(); return json({ id }, 201); }
    if (url.pathname === '/api/dictionary/words' && request.method === 'GET') { const rows = await env.DB.prepare('SELECT * FROM words ORDER BY updated_at DESC LIMIT 200').all(); return json({ items: rows.results }); }
    if (url.pathname === '/api/dictionary/words' && request.method === 'POST') { if(!requireParentSession(request)) return json({ error:'parent_session_required' }, 401); const body=await readJson(request); const errors=validateWord(body); if(errors.length) return json({ errors }, 400); const id=body.id || crypto.randomUUID(); await env.DB.prepare('INSERT INTO words (id,word,speech_text,category_id,difficulty,emoji,target_character_id,enabled,source_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,datetime("now"),datetime("now"))').bind(id, body.word, body.speech_text, body.category_id||null, body.difficulty, body.emoji||null, body.target_character_id||null, body.enabled===false?0:1, body.source_id||null).run(); return json({ id }, 201); }
    if (url.pathname === '/api/import/document' && request.method === 'POST') { if(!requireParentSession(request)) return json({ error:'parent_session_required' }, 401); return json({ status:'pending_review', message:'DOCX and selectable-text PDF imports must create candidates first; scanned PDFs require OCR and are not accepted in V1.3.0.' }, 202); }
    return json({ error:'not_found' }, 404); } };
